/*
 * BookAddInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.hellozepp.view;

import com.hellozepp.dao.UserDao;
import com.hellozepp.model.User;
import com.hellozepp.util.DbUtil;
import com.hellozepp.util.StringUtil;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.sql.Connection;

/**
 * @author __USER__
 */
public class EmpoleeAddInterFrm extends javax.swing.JInternalFrame {
    DbUtil dbUtil = new DbUtil();
    UserDao bookDao = new UserDao();

    /**
     * Creates new form BookAddInterFrm
     */
    public EmpoleeAddInterFrm() {
        initComponents();
        this.setLocation(200, 50);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        name = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("\u6DFB\u52A0\u5458\u5DE5");

        name.setText("\u59D3\u540D\uFF1A");

        jLabel2.setText("\u7528\u6237\u540D\uFF1A");

        jLabel4.setText("\u5BC6\u7801\uFF1A");

        jButton1.setIcon(new javax.swing.ImageIcon(MainFrm.imagePath + "add.png"));
        jButton1.setText("添加");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(MainFrm.imagePath + "reset.png"));
        jButton2.setText("重置");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(55)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(name)
        							.addGap(53)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(nameTxt, GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        								.addGroup(layout.createSequentialGroup()
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(passwordTxt)))
        							.addGap(63)
        							.addComponent(jLabel2)
        							.addGap(45)
        							.addComponent(userNameTxt, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(69)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        					.addGap(45)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(32)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(name)
        				.addComponent(nameTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2)
        				.addComponent(userNameTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(35)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(passwordTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(94)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton2)
        				.addComponent(jButton1))
        			.addContainerGap(36, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    //GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String name = this.nameTxt.getText();
        String userName = this.userNameTxt.getText();
        String password = this.passwordTxt.getText();

        if (StringUtil.isEmpty(userName)) {
            JOptionPane.showMessageDialog(null, "账号不能为空！");
            return;
        }
        if (StringUtil.isEmpty(name)) {
            JOptionPane.showMessageDialog(null, "姓名不能为空！");
            return;
        }
        if (StringUtil.isEmpty(password)) {
            JOptionPane.showMessageDialog(null, "密码不能为空！");
            return;
        }
        User book = new User(name, userName, password);

        Connection con = null;
        try {
            con = dbUtil.getCon();
            int addNum = bookDao.Add(con, book);
            if (addNum == 1) {
                JOptionPane.showMessageDialog(null, "店员添加成功！");
                this.resetValue();
            } else {
                JOptionPane.showMessageDialog(null, "店员添加失败！");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "店员添加失败！");
        } finally {
            try {
                dbUtil.closeCon(con);
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }


    private void resetValue() {
        this.nameTxt.setText("");
        this.userNameTxt.setText("");
        this.passwordTxt.setText("");
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.resetValue();
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField passwordTxt;
}