/*
 * HelpInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.hellozepp.view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author  __USER__
 */
public class HelpInterFrm extends javax.swing.JInternalFrame {

	/** Creates new form HelpInterFrm */
	public HelpInterFrm() {
		initComponents();
		this.setLocation(200, 50);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setTitle("\u5173\u4E8E\u56FE\u4E66\u7BA1\u7406\u7CFB\u7EDF");

		jLabel1.setIcon(new javax.swing.ImageIcon(
				MainFrm.imagePath+"java1234.png"));

		jLabel5.setFont(new java.awt.Font("΢���ź�", 0, 18));
		jLabel5
				.setText("\u5F53\u524D\u7248\u672C 0.0.1   \r\n\u8BED\u8A00\uFF1Ajava     \r\n\u7F16\u7801\uFF1AGBK     \r\n");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(25)
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addGap(92)
							.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 426, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(84, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(44)
					.addComponent(jLabel1)
					.addGap(26)
					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(146, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables

}