/*
 * MainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.hellozepp.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

import com.hellozepp.model.User;
import com.hellozepp.model.Enum.UserTypeEnum;

/**
 * @author __USER__
 */
public class MainFrm extends javax.swing.JFrame {
        public static final String imagePath = "."+ File.separator+"image"+File.separator;
//    public static final String imagePath = "/opt/projects/javaGUI/BookManger/src/com/hellozepp/view/image/";
    public static User user;

    /**
     * Creates new form MainFrm
     *
     * @param user
     */
    public MainFrm(User user) {
        MainFrm.user = user;
        initComponents();
        // 设置最大化
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        table = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmiBookTypeAdd = new javax.swing.JMenuItem();
        jmiBookTypeManage = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiBookAdd = new javax.swing.JMenuItem();
        jmiBookManage = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiaboutJava1234 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("图书管理系统主界面");

        jMenu1.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "base.png"));
        jMenu1.setText("基本数据维护");

        jMenu3.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "bookTypeManager.png"));
        jMenu3.setText("图书类别管理");

        jmiBookTypeAdd.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "add.png"));
        jmiBookTypeAdd.setText("添加图书类别");
        jmiBookTypeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBookTypeAddActionPerformed(evt);
            }
        });
        jMenu3.add(jmiBookTypeAdd);

        jmiBookTypeManage.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "edit.png"));
        jmiBookTypeManage.setText("图书类别维护");
        jmiBookTypeManage
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jmiBookTypeManageActionPerformed(evt);
                    }
                });
        jMenu3.add(jmiBookTypeManage);

        jMenu1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "bookManager.png"));
        jMenu4.setText("图书管理");

        jmiBookAdd.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "add.png"));
        jmiBookAdd.setText("添加图书");
        jmiBookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBookAddActionPerformed(evt);
            }
        });
        jMenu4.add(jmiBookAdd);

        jmiBookManage.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "edit.png"));
        jmiBookManage.setText("图书维护");
        jmiBookManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBookManageActionPerformed(evt);
            }
        });
        jMenu4.add(jmiBookManage);

        jMenu1.add(jMenu4);

        jmiExit.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "exit.png"));
        jmiExit.setText("退出系统");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });

        menuItem = new JMenuItem();
        menuItem.setText("租赁信息");
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jmiLeasePerformed(e);
            }
        });
        jMenu1.add(menuItem);

        employeeMenu = new JMenu();
        if (!UserTypeEnum.ADMIN.getName().equals(user.getUserType())) {
            employeeMenu.setEnabled(false);
        } else {
            employeeMenu.setEnabled(true);
        }
        employeeMenu.setText("员工管理");
        jMenu1.add(employeeMenu);

        addEmployeeItem = new JMenuItem();
        addEmployeeItem.setText("添加员工");
        addEmployeeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmpoleeAddInterFrmPerformed(evt);
            }
        });
        employeeMenu.add(addEmployeeItem);

        employeeListItem = new JMenuItem();
        employeeListItem.setText("员工列表");
        employeeListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmpoleeInterFrmPerformed(evt);
            }
        });
        employeeMenu.add(employeeListItem);
        jMenu1.add(jmiExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "about.png"));
        jMenu2.setText("Help");

        jmiaboutJava1234.setIcon(new javax.swing.ImageIcon(
                MainFrm.imagePath + "me.png"));
        jmiaboutJava1234.setText("about 图书管理系统");
        jmiaboutJava1234.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiaboutJava1234ActionPerformed(evt);
            }
        });
        jMenu2.add(jmiaboutJava1234);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
                javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
                javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE));

        pack();
    }// </editor-fold>

    //GEN-END:initComponents

    private void jmiaboutJava1234ActionPerformed(java.awt.event.ActionEvent evt) {
        HelpInterFrm helpInterFrm = new HelpInterFrm();
        helpInterFrm.setVisible(true);
        this.table.add(helpInterFrm);
    }

    private void jmiBookManageActionPerformed(java.awt.event.ActionEvent evt) {
        BookManageInterFrm BookManageInterFrm = new BookManageInterFrm();
        BookManageInterFrm.setVisible(true);
        this.table.add(BookManageInterFrm);
    }

    private void jmiBookAddActionPerformed(java.awt.event.ActionEvent evt) {
        BookAddInterFrm BookAddInterFrm = new BookAddInterFrm();
        BookAddInterFrm.setVisible(true);
        this.table.add(BookAddInterFrm);
    }

    private void jmiBookTypeManageActionPerformed(java.awt.event.ActionEvent evt) {
        BookTypeManageInterFrm BookTypeManageInterFrm = new BookTypeManageInterFrm();
        BookTypeManageInterFrm.setVisible(true);
        this.table.add(BookTypeManageInterFrm);
    }

    private void jmiBookTypeAddActionPerformed(java.awt.event.ActionEvent evt) {
        BookTypeInterFrm bookTypeInterFrm = new BookTypeInterFrm();
        bookTypeInterFrm.setVisible(true);
        this.table.add(bookTypeInterFrm);
    }

    private void jmiLeasePerformed(ActionEvent evt) {
        LeaseInterFrm bookTypeInterFrm = new LeaseInterFrm();
        bookTypeInterFrm.setVisible(true);
        this.table.add(bookTypeInterFrm);
    }

    private void jmiEmpoleeInterFrmPerformed(ActionEvent evt) {
        EmpoleeInterFrm bookTypeInterFrm = new EmpoleeInterFrm();
        bookTypeInterFrm.setVisible(true);
        this.table.add(bookTypeInterFrm);
    }

    private void jmiEmpoleeAddInterFrmPerformed(ActionEvent evt) {
        EmpoleeAddInterFrm bookTypeInterFrm = new EmpoleeAddInterFrm();
        bookTypeInterFrm.setVisible(true);
        this.table.add(bookTypeInterFrm);
    }

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {
        int result = JOptionPane.showConfirmDialog(null, "是否退出系统");
        if (result == 0) {
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm(user).setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiBookAdd;
    private javax.swing.JMenuItem jmiBookManage;
    private javax.swing.JMenuItem jmiBookTypeAdd;
    private javax.swing.JMenuItem jmiBookTypeManage;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiaboutJava1234;
    private javax.swing.JDesktopPane table;
    private JMenuItem menuItem;
    private JMenu employeeMenu;
    private JMenuItem addEmployeeItem;
    private JMenuItem employeeListItem;
    // End of variables declaration//GEN-END:variables

}